language: java
jdk:
  - oraclejdk8
script:
    - ./gradlew build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
