version: '2'
services:
    userservice-postgresql:
        container_name: userservice-postgresql
        image: postgres:9.5.2
        # volumes:
        #     - ~/volumes/jhipster/UserService/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=UserService
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
